//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingManagementSystem.WebForms.Client.Accounts
{


    public partial class ManageAccounts
    {

        /// <summary>
        /// pnlAccountList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlAccountList;
        protected global::System.Web.UI.WebControls.Panel pnlAccountDetails;

        /// <summary>
        /// ddlAccountType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlAccountType;

        /// <summary>
        /// btnAddAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnAddAccount;

        /// <summary>
        /// gvAccounts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvAccounts;

        /// <summary>
        /// pnlCoHolderDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlCoHolderDetails;

        /// <summary>
        /// txtCoHolderName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCoHolderName;

        /// <summary>
        /// txtCoHolderClientId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCoHolderClientId;

        /// <summary>
        /// txtCoHolderMobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCoHolderMobile;

        /// <summary>
        /// pnlAccountDetails control.
        /// </summary>

        /// <summary>
        /// ddlNewAccountType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNewAccountType;

        /// <summary>
        /// ddlIsJointAccount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlIsJointAccount;

        /// <summary>
        /// fsJointAccount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel fsJointAccount;

        /// <summary>
        /// txtJointClientId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtJointClientId;

        /// <summary>
        /// pnlBntsEditUpdateDlt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBtnsEditUpdateDlt;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// btnEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEdit;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;
    }
}
