//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingManagementSystem.WebForms.SignUp.Link
{


    public partial class ClientSignupCreateAccountLinkAccount
    {

        protected global::System.Web.UI.WebControls.TextBox txtAccountNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlAccountType;
        protected global::System.Web.UI.WebControls.TextBox txtMobileNumber;
        protected global::System.Web.UI.WebControls.TextBox txtEmailId;
        protected global::System.Web.UI.WebControls.TextBox txtClientId;
        protected global::System.Web.UI.WebControls.DropDownList ddlIsJointAccount;
        protected global::System.Web.UI.WebControls.Panel fsJointAccount;
        protected global::System.Web.UI.WebControls.TextBox txtCoholderClientId;
        protected global::System.Web.UI.WebControls.TextBox txtCoholderMobile;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkBoxTerms;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
